Repository schubergphilis/terraform-aws-mcaf-datadog, pull requests merged in 2024-07, with the labels that each got.

#27 feat: enable Datadog resource collection for cloud security
  README.md
  main.tf
  variables.tf
Labels: enhancement, feature

#28 fix: correct policy ARN
  main.tf
Labels: bug

#29 feature: Add metrics tag filter
  README.md
  main.tf
  variables.tf
Labels: documentation, feature
